FROM node:20-alpine3.19
RUN apk add --no-cache g++ make py3-pip supervisor bash caddy
RUN npm --no-update-notifier --no-fund --global install pnpm@10.6.1 pm2

# Augmenter la mémoire disponible pour Node.js
ENV NODE_OPTIONS="--max-old-space-size=4096"

WORKDIR /app

# Copier tous les fichiers nécessaires
COPY . /app

# Copier les fichiers Docker
COPY var/docker/supervisord.conf /etc/supervisord.conf
COPY var/docker/Caddyfile /app/Caddyfile
COPY var/docker/entrypoint.sh /app/entrypoint.sh
COPY var/docker/start.sh /app/start.sh
COPY var/docker/build.sh /app/build.sh
COPY var/docker/supervisord/caddy.conf /etc/supervisor.d/caddy.conf
RUN chmod +x /app/entrypoint.sh
RUN chmod +x /app/start.sh
RUN chmod +x /app/build.sh

# Installer les dépendances sans le script postinstall
RUN pnpm install --no-frozen-lockfile --ignore-scripts

# Exécuter les scripts nécessaires manuellement
RUN pnpm run update-plugins
RUN pnpm run prisma-generate

# Build avec le script personnalisé
RUN /app/build.sh

EXPOSE 4200 3000

# Utiliser le script de démarrage personnalisé
CMD ["/app/start.sh"]
